### ISSUE TITLE
Failed to compile from source code

### ISSUE THREAD

**Issue by zhaiwx1987** [facebook/mysql-5.6#272]
1. MADV_DONTDUMP on my testing platform is not supported, so error will be throw out while compiling  

```
/home/yinfeng.zwx/fb-mysql-5.6/storage/innobase/os/os0proc.cc: In function ‘void* os_mem_alloc_large(ulint*, ulint)’:
/home/yinfeng.zwx/fb-mysql-5.6/storage/innobase/os/os0proc.cc:209:23: error: ‘MADV_DONTDUMP’ was not declared in this scope
    madvise(ptr, size, MADV_DONTDUMP);
                       ^
/home/yinfeng.zwx/fb-mysql-5.6/storage/innobase/os/os0proc.cc: In function ‘void os_mem_free_large(void*, ulint)’:
/home/yinfeng.zwx/fb-mysql-5.6/storage/innobase/os/os0proc.cc:292:23: error: ‘MADV_DODUMP’ was not declared in this scope
```

Suggested Fix:   Check if MADV_DODUMP is supported in `storage/innobase/CMakeLists.txt`
1.  `-lrt` need to be specified, or another error happens:  

```
librocksdb_se.a(env_posix.cc.o): In function `NowNanos':
/home/yinfeng.zwx/fb-mysql-5.6/rocksdb/util/env_posix.cc:588: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[2]: *** [storage/rocksdb/ldb] Error 1
make[1]: *** [storage/rocksdb/CMakeFiles/ldb.dir/all] Error 2
```

**Comment by mdcallag** [comment]
What is your testing platform? I have a mix of CentOS and Ubuntu 14.04

**Comment by mdcallag** [comment]
HEAD still builds on Ubuntu 14.04. The library list from cmake is:
 Library mysqlserver depends on OSLIBS -lpthread;m;rt;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;dl;crypt;aio;snappy;lz4;bz2

**Comment by gunnarku** [comment]
@zhaiwx1987 - could you please follow the steps at https://github.com/facebook/mysql-5.6/wiki/Reporting-bugs-and-asking-for-help and give us necessary information so that we can try to reproduce on the relevant platform, fix, and validate as necessary?

**Comment by pengtfb** [comment]
Commenting out the madvise() call will unblock you. This is for dropping large memory buffers before dumping cores for InnoDB, MyRocks doesn't need it.

**Comment by zhaiwx1987** [comment]
@mdcallag @gunnarku 

We are running a heavy patched redhat6 on our production/dev environment 

```
$uname -a
Linux 2.6.32-358.23.2.ali1195.el6.x86_64 #1 SMP Wed Oct 29 20:23:37 CST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

gcc/g++ Version

```
$/opt/rh/devtoolset-2/root/usr/bin/g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

$/opt/rh/devtoolset-2/root/usr/bin/gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
```

And I am using our standard script to build the source code:

```
COMMON_FLAGS="-O3 -g -fexceptions -fno-omit-frame-pointer -fno-strict-aliasing "
CFLAGS="$COMMON_FLAGS"
CXXFLAGS="$COMMON_FLAGS "
CC=/opt/rh/devtoolset-2/root/usr/bin/gcc
CXX=/opt/rh/devtoolset-2/root/usr/bin/g++
export CC CXX CFLAGS CXXFLAGS

rm -rf CMakeCache.txt
make clean

cmake .                              \
    -DCMAKE_BUILD_TYPE="$build_type"   \
    -DSYSCONFDIR="$dest_dir"           \
    -DCMAKE_INSTALL_PREFIX="$dest_dir" \
    -DMYSQL_DATADIR="$dest_dir/data"   \
    -DWITH_DEBUG=$debug                \
    -DWITH_DEBUG_SYNC=$debug_sync      \
    -DINSTALL_LAYOUT=STANDALONE        \
    -DMYSQL_MAINTAINER_MODE=0          \
    -DWITH_EMBEDDED_SERVER=0           \
    -DWITH_EXTRA_CHARSETS=all          \
    -DWITH_SSL=system                 \
    -DWITH_ZLIB=bundled                \
    -DWITH_MYISAM_STORAGE_ENGINE=1     \
    -DWITH_INNOBASE_STORAGE_ENGINE=1   \
    -DBUILD_TESTING=OFF                 \
    -DUSE_CTAGS=0                      \
    -DENABLE_DTRACE=0                  \
    -DENABLED_PROFILING=0              \
    -DENABLED_LOCAL_INFILE=1           \
    -DMYSQL_SERVER_SUFFIX="$server_suffix"
```

I solved the problem after adding `-lrt` to COMMON_FLAGS

By the way, another error happens even WITH_LZ4 or WITH_SNAPPY are both not set 

```
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lsnappy
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -llz4
```

I commented out the relevant code in storage/rocksdb/CMakeLists.txt and then finally success to build it.

@pengtfb Yes, Just a small suggestion  :)

**Comment by mdcallag** [comment]
2.6.32-358 means RHEL 6.4 or CentOS equivalent -
https://access.redhat.com/articles/3078

On Sat, Jun 25, 2016 at 6:56 PM, zhaiweixiang notifications@github.com
wrote:

> @mdcallag https://github.com/mdcallag @gunnarku
> https://github.com/gunnarku
> 
> We are running a heavy patched redhat6 on our production/dev environment
> 
> $uname -a
> Linux 2.6.32-358.23.2.ali1195.el6.x86_64 #1 SMP Wed Oct 29 20:23:37 CST 2014 x86_64 x86_64 x86_64 GNU/Linux
> 
> gcc/g++ Version
> 
> $/opt/rh/devtoolset-2/root/usr/bin/g++ --version
> g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
> 
> $/opt/rh/devtoolset-2/root/usr/bin/gcc --version
> gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
> 
> And I am using our standard script to build the source code:
> 
> COMMON_FLAGS="-O3 -g -fexceptions -fno-omit-frame-pointer -fno-strict-aliasing "
> CFLAGS="$COMMON_FLAGS"
> CXXFLAGS="$COMMON_FLAGS "
> CC=/opt/rh/devtoolset-2/root/usr/bin/gcc
> CXX=/opt/rh/devtoolset-2/root/usr/bin/g++
> export CC CXX CFLAGS CXXFLAGS
> 
> rm -rf CMakeCache.txt
> make clean
> 
> cmake .                              \
>     -DCMAKE_BUILD_TYPE="$build_type"   \
>     -DSYSCONFDIR="$dest_dir"           \
>     -DCMAKE_INSTALL_PREFIX="$dest_dir" \
>     -DMYSQL_DATADIR="$dest_dir/data"   \
>     -DWITH_DEBUG=$debug                \
>     -DWITH_DEBUG_SYNC=$debug_sync      \
>     -DINSTALL_LAYOUT=STANDALONE        \
>     -DMYSQL_MAINTAINER_MODE=0          \
>     -DWITH_EMBEDDED_SERVER=0           \
>     -DWITH_EXTRA_CHARSETS=all          \
>     -DWITH_SSL=system                 \
>     -DWITH_ZLIB=bundled                \
>     -DWITH_MYISAM_STORAGE_ENGINE=1     \
>     -DWITH_INNOBASE_STORAGE_ENGINE=1   \
>     -DBUILD_TESTING=OFF                 \
>     -DUSE_CTAGS=0                      \
>     -DENABLE_DTRACE=0                  \
>     -DENABLED_PROFILING=0              \
>     -DENABLED_LOCAL_INFILE=1           \
>     -DMYSQL_SERVER_SUFFIX="$server_suffix"
> 
> I solved the problem after adding -lrt to COMMON_FLAGS
> 
> By the way, another error happens even WITH_LZ4 or WITH_SNAPPY are both
> not set
> 
> /opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lsnappy
> /opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -llz4
> 
> I commented out the relevant code in storage/rocksdb/CMakeLists.txt and
> then finally success to build it.
> 
> @pengtfb https://github.com/pengtfb Yes, Just a small suggestion :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/272#issuecomment-228579906,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABkKTcLMqRxXeplbA9ZOfBmJBe_Yjj6yks5qPdxogaJpZM4I-TNZ
> .

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by gunnarku** [comment]
Fix for the second issue is at https://reviews.facebook.net/D60063.

**Comment by gunnarku** [comment]
All these issues should be fixed now.
